import type { Capability } from "@/lib/domain";

type Seed = Omit<Capability, "id"> & { slug: string };

function node(seed: Seed): Capability {
  return { ...seed, id: seed.slug };
}

export const ONTOLOGY: Capability[] = [
  node({
    slug: "agent-systems",
    name: "Agent systems",
    parentId: null,
    description: "Systems that plan, call tools, and carry work across steps.",
    aliases: ["agents family"],
    phrases: ["agent systems"],
    category: "Agent systems",
    baseTheta: 35,
    baseVega: 60,
    adjacency: ["agents", "agent-orchestration", "tool-use"],
  }),
  node({
    slug: "agents",
    name: "Agents",
    parentId: "agent-systems",
    description: "Task-level autonomous or semi-autonomous agent behavior.",
    aliases: ["autonomous agents", "AI agents"],
    phrases: ["autonomous agents", "agent experiences"],
    category: "Agent systems",
    baseTheta: 42,
    baseVega: 58,
    adjacency: ["agent-orchestration", "tool-use", "agent-evals", "planning"],
  }),
  node({
    slug: "tool-use",
    name: "Tool use",
    parentId: "agent-systems",
    description: "How agents call external tools and handle tool failure.",
    aliases: ["function calling"],
    phrases: ["tool use", "function calling"],
    category: "Agent systems",
    baseTheta: 40,
    baseVega: 55,
    adjacency: ["agents", "agent-orchestration", "reliability"],
  }),
  node({
    slug: "multi-agent-systems",
    name: "Multi-agent systems",
    parentId: "agent-systems",
    description: "Coordination across more than one agent.",
    aliases: ["multiagent"],
    phrases: ["multi-agent systems", "multiple agents"],
    category: "Agent systems",
    baseTheta: 38,
    baseVega: 57,
    adjacency: ["agent-orchestration", "planning", "agent-evals"],
  }),
  node({
    slug: "agent-orchestration",
    name: "Agent orchestration",
    parentId: "agent-systems",
    description: "Runtime control of agent graphs, handoffs, and state.",
    aliases: ["orchestration"],
    phrases: ["agent orchestration", "orchestrate agents"],
    category: "Agent systems",
    baseTheta: 30,
    baseVega: 64,
    adjacency: ["agents", "planning", "workflow-automation", "observability"],
  }),
  node({
    slug: "memory",
    name: "Memory",
    parentId: "agent-systems",
    description: "Persistent or session memory for agents.",
    aliases: ["agent memory"],
    phrases: ["agent memory", "long-term memory"],
    category: "Agent systems",
    baseTheta: 36,
    baseVega: 52,
    adjacency: ["agents", "planning", "data-infrastructure"],
  }),
  node({
    slug: "planning",
    name: "Planning",
    parentId: "agent-systems",
    description: "Decomposition, plans, and replanning.",
    aliases: ["task planning"],
    phrases: ["task planning", "plan decomposition"],
    category: "Agent systems",
    baseTheta: 28,
    baseVega: 66,
    adjacency: ["agent-orchestration", "agents", "failure-analysis"],
  }),
  node({
    slug: "workflow-automation",
    name: "Workflow automation",
    parentId: "agent-systems",
    description: "Turning a business workflow into a repeatable agent path.",
    aliases: ["workflow"],
    phrases: ["workflow automation", "business workflow"],
    category: "Agent systems",
    baseTheta: 45,
    baseVega: 50,
    adjacency: ["customer-workflows", "agent-orchestration", "productization"],
  }),
  node({
    slug: "evaluations",
    name: "Evaluations",
    parentId: null,
    description: "Measurement of model and agent behavior.",
    aliases: ["evals family"],
    phrases: ["evaluation systems"],
    category: "Evaluations",
    baseTheta: 18,
    baseVega: 86,
    adjacency: ["agent-evals", "model-evals", "statistical-evaluation", "failure-analysis"],
  }),
  node({
    slug: "evals",
    name: "Evals",
    parentId: "evaluations",
    description: "Design and operation of evaluation harnesses.",
    aliases: ["eval design"],
    phrases: ["evaluation harness", "eval design"],
    category: "Evaluations",
    baseTheta: 20,
    baseVega: 84,
    adjacency: ["agent-evals", "model-evals", "statistical-evaluation", "reliability"],
  }),
  node({
    slug: "agent-evals",
    name: "Agent evals",
    parentId: "evaluations",
    description: "Task success, trajectory, and tool-use evaluation for agents.",
    aliases: ["agent evaluation"],
    phrases: ["agent evaluation", "trajectory evaluation"],
    category: "Evaluations",
    baseTheta: 22,
    baseVega: 80,
    adjacency: ["evals", "agents", "failure-analysis", "reliability"],
  }),
  node({
    slug: "model-evals",
    name: "Model evals",
    parentId: "evaluations",
    description: "Benchmark and capability evaluation of base or post-trained models.",
    aliases: ["model evaluation"],
    phrases: ["model evaluation", "evaluate model quality"],
    category: "Evaluations",
    baseTheta: 24,
    baseVega: 74,
    adjacency: ["evals", "benchmarking", "post-training"],
  }),
  node({
    slug: "reliability",
    name: "Reliability",
    parentId: "evaluations",
    description: "Consistency of agent or model behavior under real use.",
    aliases: ["robustness"],
    phrases: ["reliability measurement", "behavioral reliability"],
    category: "Evaluations",
    baseTheta: 18,
    baseVega: 72,
    adjacency: ["evals", "failure-analysis", "observability"],
  }),
  node({
    slug: "red-teaming",
    name: "Red teaming",
    parentId: "evaluations",
    description: "Adversarial probing of failure and abuse paths.",
    aliases: ["red team"],
    phrases: ["red teaming", "adversarial testing"],
    category: "Evaluations",
    baseTheta: 26,
    baseVega: 68,
    adjacency: ["safety", "failure-analysis", "evals"],
  }),
  node({
    slug: "benchmarking",
    name: "Benchmarking",
    parentId: "evaluations",
    description: "Public or internal benchmark construction and reading.",
    aliases: ["benchmarks"],
    phrases: ["benchmark design", "benchmark suite"],
    category: "Evaluations",
    baseTheta: 55,
    baseVega: 48,
    adjacency: ["model-evals", "statistical-evaluation"],
  }),
  node({
    slug: "failure-analysis",
    name: "Failure analysis",
    parentId: "evaluations",
    description: "Taxonomies and distributions of how systems fail.",
    aliases: ["error analysis"],
    phrases: ["failure analysis", "failure distribution"],
    category: "Evaluations",
    baseTheta: 16,
    baseVega: 78,
    adjacency: ["evals", "statistical-evaluation", "agent-evals"],
  }),
  node({
    slug: "statistical-evaluation",
    name: "Statistical evaluation",
    parentId: "evaluations",
    description: "Uncertainty, intervals, and sample design for evals.",
    aliases: ["stats for evals"],
    phrases: ["statistical evaluation", "confidence interval"],
    category: "Evaluations",
    baseTheta: 12,
    baseVega: 88,
    adjacency: ["evals", "failure-analysis", "model-evals", "reliability"],
  }),
  node({
    slug: "training",
    name: "Training / post-training",
    parentId: null,
    description: "Learning signals after pretraining, including RL and feedback.",
    aliases: ["post training family"],
    phrases: ["training stack"],
    category: "Training / post-training",
    baseTheta: 25,
    baseVega: 70,
    adjacency: ["post-training", "reinforcement-learning", "synthetic-data"],
  }),
  node({
    slug: "reinforcement-learning",
    name: "Reinforcement learning",
    parentId: "training",
    description: "RL methods, environments, and optimization for language systems.",
    aliases: ["RL"],
    phrases: ["reinforcement learning", "RL environment"],
    category: "Training / post-training",
    baseTheta: 22,
    baseVega: 70,
    adjacency: ["post-training", "reward-modeling", "preference-optimization"],
  }),
  node({
    slug: "post-training",
    name: "Post-training",
    parentId: "training",
    description: "The production stack that shapes a model after pretraining.",
    aliases: ["posttraining"],
    phrases: ["post-training", "post training pipeline"],
    category: "Training / post-training",
    baseTheta: 24,
    baseVega: 73,
    adjacency: ["reinforcement-learning", "preference-optimization", "reward-modeling", "evals"],
  }),
  node({
    slug: "preference-optimization",
    name: "Preference optimization",
    parentId: "training",
    description: "Methods that learn from preferences and ranked outputs.",
    aliases: ["DPO", "RLHF"],
    phrases: ["preference optimization", "preference data"],
    category: "Training / post-training",
    baseTheta: 34,
    baseVega: 60,
    adjacency: ["post-training", "reward-modeling", "feedback-data"],
  }),
  node({
    slug: "reward-modeling",
    name: "Reward modeling",
    parentId: "training",
    description: "Models of what a good outcome is.",
    aliases: ["reward model"],
    phrases: ["reward modeling", "reward model"],
    category: "Training / post-training",
    baseTheta: 28,
    baseVega: 66,
    adjacency: ["reinforcement-learning", "preference-optimization", "evals"],
  }),
  node({
    slug: "synthetic-data",
    name: "Synthetic data",
    parentId: "training",
    description: "Generated data used for training or evaluation.",
    aliases: ["synthetic generation"],
    phrases: ["synthetic data", "generated training data"],
    category: "Training / post-training",
    baseTheta: 32,
    baseVega: 64,
    adjacency: ["data-flywheels", "post-training", "evals"],
  }),
  node({
    slug: "data-flywheels",
    name: "Data flywheels",
    parentId: "training",
    description: "Loops where product use creates the next training signal.",
    aliases: ["flywheel"],
    phrases: ["data flywheel", "usage flywheel"],
    category: "Training / post-training",
    baseTheta: 30,
    baseVega: 76,
    adjacency: ["synthetic-data", "feedback-data", "customer-workflows"],
  }),
  node({
    slug: "feedback-data",
    name: "Feedback data",
    parentId: "training",
    description: "Human or customer feedback captured as a learning signal.",
    aliases: ["feedback loops"],
    phrases: ["feedback data", "human feedback signal"],
    category: "Training / post-training",
    baseTheta: 26,
    baseVega: 68,
    adjacency: ["data-flywheels", "preference-optimization", "customer-workflows"],
  }),
  node({
    slug: "research-modeling",
    name: "Research / modeling",
    parentId: null,
    description: "Frontier research capabilities.",
    aliases: ["research family"],
    phrases: ["modeling research"],
    category: "Research / modeling",
    baseTheta: 20,
    baseVega: 62,
    adjacency: ["alignment", "frontier-modeling", "model-behavior"],
  }),
  node({
    slug: "alignment",
    name: "Alignment",
    parentId: "research-modeling",
    description: "Keeping model behavior within intended bounds.",
    aliases: ["model alignment"],
    phrases: ["model alignment", "alignment research"],
    category: "Research / modeling",
    baseTheta: 18,
    baseVega: 70,
    adjacency: ["safety", "post-training", "red-teaming"],
  }),
  node({
    slug: "safety",
    name: "Safety",
    parentId: "research-modeling",
    description: "Hazard identification and mitigation for deployed models.",
    aliases: ["AI safety"],
    phrases: ["AI safety", "safety evaluation"],
    category: "Research / modeling",
    baseTheta: 16,
    baseVega: 74,
    adjacency: ["alignment", "red-teaming", "governance"],
  }),
  node({
    slug: "multimodal",
    name: "Multimodal",
    parentId: "research-modeling",
    description: "Models and evals across text, vision, and other modalities.",
    aliases: ["vision language"],
    phrases: ["multimodal models", "vision-language"],
    category: "Research / modeling",
    baseTheta: 30,
    baseVega: 60,
    adjacency: ["frontier-modeling", "model-evals"],
  }),
  node({
    slug: "frontier-modeling",
    name: "Frontier modeling",
    parentId: "research-modeling",
    description: "Training and studying leading-edge models.",
    aliases: ["frontier models"],
    phrases: ["frontier modeling", "frontier model"],
    category: "Research / modeling",
    baseTheta: 28,
    baseVega: 64,
    adjacency: ["post-training", "model-behavior", "hpc"],
  }),
  node({
    slug: "model-behavior",
    name: "Model behavior",
    parentId: "research-modeling",
    description: "Understanding what models actually do.",
    aliases: ["behavioral analysis"],
    phrases: ["model behavior", "behavioral analysis"],
    category: "Research / modeling",
    baseTheta: 18,
    baseVega: 72,
    adjacency: ["evals", "failure-analysis", "alignment"],
  }),
  node({
    slug: "systems",
    name: "Systems",
    parentId: null,
    description: "Infrastructure underneath training and serving.",
    aliases: ["ml infra"],
    phrases: ["ML systems platform"],
    category: "Systems",
    baseTheta: 22,
    baseVega: 68,
    adjacency: ["inference", "ml-systems", "data-infrastructure"],
  }),
  node({
    slug: "inference",
    name: "Inference",
    parentId: "systems",
    description: "Serving models within latency and cost constraints.",
    aliases: ["serving"],
    phrases: ["inference serving", "inference stack"],
    category: "Systems",
    baseTheta: 34,
    baseVega: 58,
    adjacency: ["ml-systems", "distributed-systems", "observability"],
  }),
  node({
    slug: "ml-systems",
    name: "ML systems",
    parentId: "systems",
    description: "Software systems specialized for machine learning workloads.",
    aliases: ["MLSys"],
    phrases: ["ML systems", "machine learning systems"],
    category: "Systems",
    baseTheta: 24,
    baseVega: 70,
    adjacency: ["inference", "distributed-systems", "observability", "data-infrastructure"],
  }),
  node({
    slug: "distributed-systems",
    name: "Distributed systems",
    parentId: "systems",
    description: "Correctness and performance of multi-node systems.",
    aliases: ["distributed computing"],
    phrases: ["distributed systems", "distributed runtime"],
    category: "Systems",
    baseTheta: 14,
    baseVega: 72,
    adjacency: ["ml-systems", "inference", "compute-orchestration"],
  }),
  node({
    slug: "hpc",
    name: "HPC",
    parentId: "systems",
    description: "High-performance compute for training.",
    aliases: ["supercomputing"],
    phrases: ["high performance compute", "HPC cluster"],
    category: "Systems",
    baseTheta: 20,
    baseVega: 48,
    adjacency: ["compute-orchestration", "frontier-modeling"],
  }),
  node({
    slug: "observability",
    name: "Observability",
    parentId: "systems",
    description: "Traces, metrics, and logs for ML and agent systems.",
    aliases: ["monitoring"],
    phrases: ["ML observability", "trace evaluation"],
    category: "Systems",
    baseTheta: 28,
    baseVega: 66,
    adjacency: ["reliability", "ml-systems", "agent-evals"],
  }),
  node({
    slug: "data-infrastructure",
    name: "Data infrastructure",
    parentId: "systems",
    description: "Pipelines that move training, feedback, and eval data.",
    aliases: ["data infra"],
    phrases: ["data infrastructure", "data platform"],
    category: "Systems",
    baseTheta: 22,
    baseVega: 70,
    adjacency: ["data-flywheels", "ml-systems", "feedback-data"],
  }),
  node({
    slug: "compute-orchestration",
    name: "Compute orchestration",
    parentId: "systems",
    description: "Scheduling GPUs and jobs.",
    aliases: ["cluster scheduling"],
    phrases: ["compute orchestration", "GPU scheduling"],
    category: "Systems",
    baseTheta: 30,
    baseVega: 50,
    adjacency: ["hpc", "distributed-systems", "inference"],
  }),
  node({
    slug: "applied",
    name: "Applied / field",
    parentId: null,
    description: "Customer-facing and organizational application of AI.",
    aliases: ["applied AI"],
    phrases: ["applied AI practice"],
    category: "Applied / field",
    baseTheta: 24,
    baseVega: 64,
    adjacency: ["enterprise-ai", "customer-workflows", "forward-deployed-engineering"],
  }),
  node({
    slug: "forward-deployed-engineering",
    name: "Forward deployed engineering",
    parentId: "applied",
    description: "Building with customers, close to the workflow.",
    aliases: ["FDE"],
    phrases: ["forward deployed", "customer deployment engineering"],
    category: "Applied / field",
    baseTheta: 26,
    baseVega: 62,
    adjacency: ["enterprise-ai", "customer-workflows", "integration", "agent-evals"],
  }),
  node({
    slug: "enterprise-ai",
    name: "Enterprise AI",
    parentId: "applied",
    description: "Deploying AI into enterprise environments.",
    aliases: ["enterprise agents"],
    phrases: ["enterprise AI", "enterprise deployment"],
    category: "Applied / field",
    baseTheta: 28,
    baseVega: 66,
    adjacency: ["customer-workflows", "governance", "forward-deployed-engineering"],
  }),
  node({
    slug: "customer-workflows",
    name: "Customer workflows",
    parentId: "applied",
    description: "Discovering the real work a customer needs done.",
    aliases: ["workflow discovery"],
    phrases: ["customer workflow", "workflow discovery"],
    category: "Applied / field",
    baseTheta: 14,
    baseVega: 80,
    adjacency: ["enterprise-ai", "technical-solution-shaping", "workflow-automation"],
  }),
  node({
    slug: "governance",
    name: "Governance",
    parentId: "applied",
    description: "Risk, policy, and decision rights around deployed AI.",
    aliases: ["AI governance"],
    phrases: ["AI governance", "deployment risk"],
    category: "Applied / field",
    baseTheta: 18,
    baseVega: 70,
    adjacency: ["safety", "enterprise-ai", "executive-communication"],
  }),
  node({
    slug: "productization",
    name: "Productization",
    parentId: "applied",
    description: "Turning a capability into a product surface.",
    aliases: ["productizing"],
    phrases: ["productization", "product surface"],
    category: "Applied / field",
    baseTheta: 36,
    baseVega: 48,
    adjacency: ["enterprise-ai", "workflow-automation", "integration"],
  }),
  node({
    slug: "integration",
    name: "Integration",
    parentId: "applied",
    description: "Connecting agents and models to existing systems.",
    aliases: ["systems integration"],
    phrases: ["systems integration", "integration work"],
    category: "Applied / field",
    baseTheta: 30,
    baseVega: 55,
    adjacency: ["enterprise-ai", "forward-deployed-engineering", "data-infrastructure"],
  }),
  node({
    slug: "executive-communication",
    name: "Executive communication",
    parentId: "applied",
    description: "Making technical tradeoffs legible to senior stakeholders.",
    aliases: ["exec communication"],
    phrases: ["executive communication", "senior stakeholder narrative"],
    category: "Applied / field",
    baseTheta: 12,
    baseVega: 60,
    adjacency: ["governance", "technical-solution-shaping", "customer-workflows"],
  }),
  node({
    slug: "technical-solution-shaping",
    name: "Technical solution shaping",
    parentId: "applied",
    description: "Framing a customer problem into a buildable technical approach.",
    aliases: ["solution shaping"],
    phrases: ["solution shaping", "technical approach"],
    category: "Applied / field",
    baseTheta: 16,
    baseVega: 74,
    adjacency: ["customer-workflows", "enterprise-ai", "agent-orchestration"],
  }),
  node({
    slug: "cross-functional-execution",
    name: "Cross-functional execution",
    parentId: "applied",
    description: "Moving work across research, engineering, product, and customer teams.",
    aliases: ["cross functional"],
    phrases: ["cross-functional execution", "cross functional delivery"],
    category: "Applied / field",
    baseTheta: 14,
    baseVega: 68,
    adjacency: ["technical-solution-shaping", "executive-communication", "productization"],
  }),
];

export const CAPABILITY_BY_SLUG = new Map(ONTOLOGY.map((capability) => [capability.slug, capability]));

export function childrenOf(slug: string): Capability[] {
  return ONTOLOGY.filter((capability) => capability.parentId === slug);
}

export function familySlug(slug: string): string {
  const capability = CAPABILITY_BY_SLUG.get(slug);
  if (!capability) return slug;
  return capability.parentId ?? capability.slug;
}
